[package]
name = "easyrustv1"
version = "0.1.4"
edition = "2021"
author  = "jenny"
description = " this is sample sorce "
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[profile.release] 
panic = 'abort'
