workspace = { members = ["sb1", "sb2", "sb3"] }
[package]
name = "submit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
